server:
  port: 9099
  servlet:
    context-path: /redis-demo

spring:
  profiles:
    active: development-mysql
  redis:
    database: 0
    # Redis服务器地址
    host: 192.168.1.88
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: matech.2019
    jedis:
      pool:
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        #        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
      # 连接超时时间（毫秒）
    timeout: 1s
  kafka:
    bootstrap-servers: 192.168.0.5:9092
    consumer:
      group-id: test-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
matech:
  framework:
    snowflake:
      idc: 1
      machine: 1

---
spring:
  profiles: development-mysql
  datasource:
    name: MYDB
    #schema: classpath:/sql/schema-mysql.sql
    #data: classpath:/sql/data-mysql.sql
    sql-script-encoding: utf-8
    driver-class-name:   com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.88:13306/redis_demo?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=false&rewriteBatchedStatements=true&useSSL=false
    username: icm
    password: icm!2#4%6

    tomcat:
      max-active: 5
      max-idle: 3
      min-idle: 1
      initial-size: 2
      validation-query: select 1
      test-on-borrow: true
      test-on-return: false
      time-between-eviction-runs-millis: 600000
      min-evictable-idle-time-millis: 300000
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update # Hibernate ddl auto (none, create, create-drop, update, validate)
    properties:
      #      hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect    #默认使用innodb引擎
      hibernate.format_sql: true
      hibernate.max_fetch_depth: 1
      hibernate.generate_statistics: false
      hibernate.use_sql_comments: true